# Generated by Django 5.0.2 on 2024-04-04 21:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado')], max_length=50, verbose_name='Nombre del Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la marca')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('mano_de_obra', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor de mano de obra')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Valor total')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bicicleteria.estadobicicleta')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicleteria.marca', verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('idGarantia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('fecha_terminacion', models.DateField(verbose_name='Fecha de terminación')),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicleteria.bicicleta', verbose_name='Bicicleta')),
            ],
        ),
    ]
