# Generated by Django 5.0.2 on 2024-02-23 08:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
