# Generated by Django 5.0.2 on 2024-02-23 08:42

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteria', '0002_bicicleta_fecha_bicicleta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='precio',
            field=models.DecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
    ]
