# Generated by Django 5.0.2 on 2024-02-23 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteria', '0003_alter_bicicleta_fecha_alter_bicicleta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
    ]
