# Generated by Django 5.0.2 on 2024-02-23 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteria', '0004_alter_bicicleta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso'),
        ),
    ]
