# Generated by Django 5.0.2 on 2024-02-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteria', '0005_alter_bicicleta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='estado',
            field=models.CharField(max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
