# Generated by Django 5.0.2 on 2024-02-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteria', '0006_bicicleta_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado')], max_length=50, verbose_name='Nombre del Estado')),
            ],
        ),
    ]
