# Generated by Django 5.0.2 on 2024-02-28 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteria', '0008_alter_bicicleta_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('idGarantia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_terminacion', models.DateField(verbose_name='Fecha de terminación')),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicleteria.bicicleta', verbose_name='Bicicleta')),
            ],
        ),
    ]
