# Generated by Django 5.0.2 on 2024-04-03 16:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteria', '0009_garantia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la marca')),
            ],
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='mano_de_obra',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor de mano de obra'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicleteria.marca', verbose_name='Marca'),
        ),
    ]
